name: Update Token Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 使用更稳定的 Python 3.9
        cache: 'pip'  # 启用 pip 缓存
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tracker
      run: python main.py
    
    - name: Commit changes
      run: |
        git config --local user.email "weinizhidao@lidao.pro"
        git config --local user.name "weinikown"
        git add data/ logs/ README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update token data $(date +'%Y-%m-%d')" && git push)